#ifndef ERROR_MSG_H

# define ERROR_MSG_H

# define ERR_USAGE			"Usage: ./fdf MAP_FILE"
# define ERR_MAP			"INCORRECT MAP_FILE"
# define ERR_MAP_READING	"MAP READING ERROR"
# define ERR_MAP_INIT		"MAP INITIALIZATION ERROR"
# define ERR_FDF_INIT		"FDF INITIALIZATION ERROR"
# define ERR_CONV_TO_ARR	"CONVERSION TO AN ARRAY ERROR"
# define ERR_CAMERA_INIT	"CAMERA INITIALIZATION ERROR"

#endif